spring:
  application:
    name: Spring-shop
  profiles:
    active: local
  jta:
    enabled: false
  jpa:
    open-in-view: false
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  cache: 
    jcache:
      config: classpath:cache/ehcache.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tresdur
    #force data.sql script execution
    initialization-mode: always
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.training.samples.spring.shop: INFO
